syntax = "proto3";
package pb;

//账号
message Account{
}

//设置
message Setting{
  optional string language = 1;
  optional int32 appearance = 2;
  optional int32 resolution = 3;
  optional float mainVolume = 4;
  optional float musicVolume = 5;
  optional float soundVolume = 6;
}

message Player{
  optional int32 money = 1;     //金币
  optional int32 diamond = 2;   //钻石
  optional int32 roleId = 3; 	  //当前玩角色Id
  optional float hp = 4;        //当前血量
  optional float maxHP = 5;     //最大血量
  optional float magic = 6;     //当前魔法
  optional float maxMagic = 7;  //最大魔法
  optional int32 exp = 8;   	  //经验
}

message DefeatRole{
  optional int32 id = 1;				//击败的角色Id
  optional int32 diff= 2;				//难度
}

message Barrier{
  repeated int32 pokerPile = 1;     	//牌堆
  repeated int32 npcPokers = 2;     	//npc的牌 
  repeated int32 playerPokers = 3;  	//player的牌
  repeated int32 otherPokers = 4;  	  //其他的牌
  optional int32 state = 5;           //状态 0发牌 1组合 2要牌
  optional int32 matchPointA = 6;     //公共牌的值
  optional int32 matchPointB = 7;     //手牌的值
  optional int32 pokerPosX = 8;  	    //坐标的偏差
  optional int32 pokerPosY = 9;        //坐标的偏差
  optional int32 finalPoint = 10;       //最终的点数
  optional int32 blackjack = 11;          //blackjack
  optional int32 chapterId = 12;             //当前章节id
  optional int32 barrierId = 13;             //关卡id
  optional int32 refreshNpcPokerNum = 14;    //刷新npc的牌次数
  optional int32 refreshPlayerPokerNum = 15; //刷新玩家的牌次数
}

message Shop{
  repeated int32 goods = 1;        //商品
  repeated int32 purchased = 2;   //已购买列表
}
message ExtraInfo{
  optional float multATK = 1;  //下次攻击额外造成伤害
  optional float addCrit = 2;  //固定增加暴击率
  optional float reflectDMG = 3;//受到攻击时反弹%s点伤害
  optional float bonusArmor = 4;//下次转化方块属性，额外获得的护甲
  optional float temporaryArmor = 5;//获得当前护甲 %s% 的临时护甲
  optional float lifeSteal = 6; //下一次造成伤害的转化为回血
  repeated float healOverTime = 7;//接下来的2回合每回合回复%s点生命值
  optional float healSuper = 8;//回复 %s 点生命值，一场战斗仅生效一次
  optional float healtoMP = 9;//下次转化红桃属性，治疗量的 %s 额外转化为法力值
  optional float skillDamageUp = 10;//下次技能效果提升 %s，可叠加
  repeated float mpRegen = 11;//接下来的3回合每回合回复 %s 点法力
  optional float mpMaxSub = 12;//本局技能释放所需 MP 减少 %s
  optional float addBleeding = 100;//下次普通攻击使敌方获得 3 层流血状态
  optional float doubleProc = 101;//下次普通攻击连续触发两次
  optional float ignoreArmor = 102;//下次普通攻击无视对手护甲
  optional float execute = 103;//下次普通攻击时若对手血量低于 15% 直接处决
  optional float retainATK = 104;//若下次普通攻击暴击，则保留50%的攻击力
  optional float reflectPercent = 105;//将下次对手普通攻击的 50% 反弹给对手
  optional float magicImmunity = 106;//获得 1个技能免疫的护盾，无法叠加
  optional float armorATK = 107;//每次获得护甲对对手造成 5 点伤害
  optional float immunityDeBuff = 108;//下回合免疫负面状态的伤害
  optional float freezeArmor = 109;//下次消耗的护甲会完全恢复
  optional float removeDeBuff = 110;//随机移除自身 1 个/层负面状态
  optional float overHealATK = 111;//下次溢出的治疗量转化为等额攻击力
  optional float healToDMG = 112;//下次治疗效果改为对对手造成等量伤害
  optional float healBoost = 113;//下次治疗效果提升50%
  optional float rebirth = 114;//受到致命伤时保留 1 血并回复 50点法力值
  optional float conversionDecline = 115;//使对手下次属性转化效率降低 50%
  optional float mPRefund = 116;//技能释放后返还 30% 消耗
  optional float mPBurn = 117;//下次对对手造成普通攻击伤害时扣除对手等量法力值
  optional float mPMaxLower = 118;//下次技能释放后释放技能所需 MP 永久减少5
  optional float doubleCast = 119;//下次技能释放将触发两次
}

//战斗的资产
message AssetInfo{
  optional int32 state = 1;
  repeated int32 pokers = 2;    //牌 
  repeated int32 cards = 3;  	  //卡
  optional float hp = 4;        //当前血量
  optional float maxHP = 5;     //最大血量
  optional float magic = 6;     //当前魔法
  optional float maxMagic = 7;  //最大魔法
  optional float attack = 8;    //攻击力
  optional float defense = 9;   //防御力
  optional int32 isFilp = 10;   //是否翻面
  optional ExtraInfo extra = 11; //额外数据
}

//战斗
message Fight{
  repeated int32 pokerPile = 1;     	 //牌堆
  optional AssetInfo npcAsset = 2;     //npc的资产
  optional AssetInfo playerAsset = 3;  //player的资产
  optional int32 state = 4;            //状态
  optional int32 round = 5;            //轮
}

//印记
message AssembleCard{
  optional int32 triggerId = 1;         //触发Id
  optional int32 baseEffectId = 2;      //基础效果Id
  optional int32 advancedEffectId = 3;  //升级效果Id
  optional int32 triggerNumber = 4;     //触发次数
  optional int32 upgradeNumber = 5;     //升级需要次数
}


//印记
message Imprint{
  optional int32 assembleObject = 1;      //正在组装的人, 0npc 1玩家
  repeated AssembleCard npcCards = 2;      //npc的资产
  repeated AssembleCard playerCards = 3;   //player的资产
}

//游戏
message GameData{
  optional int32 initSeed = 1;
  optional int32 gameState = 2;
  optional int32 pageIndex = 3;		
  optional Player player = 4;             //玩家信息
  optional Barrier barrier = 5;           //关卡
  optional Shop shop = 6;                 //商店
  optional Fight fight = 7;               //战斗  
  optional Imprint imprint = 8;           //印记
  repeated DefeatRole defeatRoles = 9;    //击败的
}

//游戏财产
message GameProperty{
  optional Account account = 1;
  optional Setting setting = 2;
  optional GameData gameData = 3;
}

//protoc --proto_path=. --csharp_out=. proto.proto
