syntax = "proto3";
package pb;

//账号
message Account{
}

//设置
message Setting{
  optional string language = 1;
  optional int32 appearance = 2;
  optional int32 resolution = 3;
  optional float mainVolume = 4;
  optional float musicVolume = 5;
  optional float soundVolume = 6;
}

message Player{
  optional int32 money = 1;     //金币
  optional int32 diamond = 2;   //钻石
  optional int32 roleId = 3; 	  //当前玩角色Id
  optional float hp = 4;        //当前血量
  optional float maxHP = 5;     //最大血量
  optional float magic = 6;     //当前魔法
  optional float maxMagic = 7;  //最大魔法
  optional int32 exp = 8;   	  //经验
}

message DefeatRole{
  optional int32 id = 1;				//击败的角色Id
  optional int32 diff= 2;				//难度
}

message Barrier{
  repeated int32 pokerPile = 1;     	//牌堆
  repeated int32 npcPokers = 2;     	//npc的牌 
  repeated int32 playerPokers = 3;  	//player的牌
  repeated int32 otherPokers = 4;  	  //其他的牌
  optional int32 state = 5;           //状态 0发牌 1组合 2要牌
  optional int32 matchPointA = 6;     //公共牌的值
  optional int32 matchPointB = 7;     //手牌的值
  optional int32 pokerPosX = 8;  	    //坐标的偏差
  optional int32 pokerPosY = 9;        //坐标的偏差
  optional int32 finalPoint = 10;       //最终的点数
  optional int32 blackjack = 11;          //blackjack
  optional int32 chapterId = 12;             //当前章节id
  optional int32 barrierId = 13;             //关卡id
  optional int32 refreshNpcPokerNum = 14;    //刷新npc的牌次数
  optional int32 refreshPlayerPokerNum = 15; //刷新玩家的牌次数
}

message Shop{
  repeated int32 goods = 1;        //商品
  repeated int32 purchased = 2;   //已购买列表
}

message BaseEffectValue{
  optional int32 type = 1;//类型
  optional float value = 2;//值
  optional float maxValue = 3;//最大值 
}

//效果值
message BaseEffectData{
  optional int32 id = 1;//ID  
  optional int32 state = 2;//0:无 1:有
  repeated BaseEffectValue baseEffectValues = 3;//效果
}

message ExtraInfo{
  //运行过程中数据
  optional float rtFreezeArmorValue = 1001;//消耗的护甲
  optional float rtAddDefenseValue = 1002;//添加的护甲值
  repeated BaseEffectData baseEffectDatas = 1003;//效果值
}

//战斗的资产
message AssetInfo{
  optional int32 state = 1;
  repeated int32 pokers = 2;    //牌 
  optional float hp = 3;        //当前血量
  optional float maxHP = 4;     //最大血量
  optional float magic = 5;     //当前魔法
  optional float maxMagic = 6;  //最大魔法
  optional float attack = 7;    //攻击力
  optional float defense = 8;   //防御力
  optional int32 isFilp = 9;   //是否翻面
  optional ExtraInfo extra = 10; //额外数据
}

//战斗
message Fight{
  repeated int32 pokerPile = 1;     	 //牌堆
  optional AssetInfo npcAsset = 2;     //npc的资产
  optional AssetInfo playerAsset = 3;  //player的资产
  optional int32 state = 4;            //状态
  optional int32 round = 5;            //轮
}

//印记
message AssembleCard{
  optional int32 triggerId = 1;         //触发Id
  optional int32 baseEffectId = 2;      //基础效果Id
  optional int32 advancedEffectId = 3;  //升级效果Id
  optional int32 triggerNumber = 4;     //触发次数
  optional int32 upgradeNumber = 5;     //升级需要次数
}


//印记
message Imprint{
  optional int32 assembleObject = 1;      //正在组装的人, 0npc 1玩家
  repeated AssembleCard npcCards = 2;      //npc的资产
  repeated AssembleCard playerCards = 3;   //player的资产
}

//游戏
message GameData{
  optional int32 initSeed = 1;
  optional int32 gameState = 2;
  optional int32 pageIndex = 3;		
  optional Player player = 4;             //玩家信息
  optional Barrier barrier = 5;           //关卡
  optional Shop shop = 6;                 //商店
  optional Fight fight = 7;               //战斗  
  optional Imprint imprint = 8;           //印记
  repeated DefeatRole defeatRoles = 9;    //击败的
}

//游戏财产
message GameProperty{
  optional Account account = 1;
  optional Setting setting = 2;
  optional GameData gameData = 3;
}

//protoc --proto_path=. --csharp_out=. proto.proto
