// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb {

  /// <summary>Holder for reflection information generated from proto.proto</summary>
  public static partial class ProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for proto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgtwcm90by5wcm90bxICcGIiCQoHQWNjb3VudCL5AQoHU2V0dGluZxIVCghs",
            "YW5ndWFnZRgBIAEoCUgAiAEBEhcKCmFwcGVhcmFuY2UYAiABKAVIAYgBARIX",
            "CgpyZXNvbHV0aW9uGAMgASgFSAKIAQESFwoKbWFpblZvbHVtZRgEIAEoAkgD",
            "iAEBEhgKC211c2ljVm9sdW1lGAUgASgCSASIAQESGAoLc291bmRWb2x1bWUY",
            "BiABKAJIBYgBAUILCglfbGFuZ3VhZ2VCDQoLX2FwcGVhcmFuY2VCDQoLX3Jl",
            "c29sdXRpb25CDQoLX21haW5Wb2x1bWVCDgoMX211c2ljVm9sdW1lQg4KDF9z",
            "b3VuZFZvbHVtZSJGChBEZWZlYXRQbGF5ZXJSb2xlEg8KAmlkGAEgASgFSACI",
            "AQESEQoEZGlmZhgCIAEoBUgBiAEBQgUKA19pZEIHCgVfZGlmZiKCBAoHQmFy",
            "cmllchIRCglwb2tlclBpbGUYASADKAUSEQoJbnBjUG9rZXJzGAIgAygFEhQK",
            "DHBsYXllclBva2VycxgDIAMoBRITCgtvdGhlclBva2VycxgEIAMoBRISCgVz",
            "dGF0ZRgFIAEoBUgAiAEBEhgKC21hdGNoUG9pbnRBGAYgASgFSAGIAQESGAoL",
            "bWF0Y2hQb2ludEIYByABKAVIAogBARIWCglwb2tlclBvc1gYCCABKAVIA4gB",
            "ARIWCglwb2tlclBvc1kYCSABKAVIBIgBARIXCgpmaW5hbFBvaW50GAogASgF",
            "SAWIAQESFgoJY2hhcHRlcklkGAsgASgFSAaIAQESFgoJYmFycmllcklkGAwg",
            "ASgFSAeIAQESHwoScmVmcmVzaE5wY1Bva2VyTnVtGA0gASgFSAiIAQESIgoV",
            "cmVmcmVzaFBsYXllclBva2VyTnVtGA4gASgFSAmIAQFCCAoGX3N0YXRlQg4K",
            "DF9tYXRjaFBvaW50QUIOCgxfbWF0Y2hQb2ludEJCDAoKX3Bva2VyUG9zWEIM",
            "CgpfcG9rZXJQb3NZQg0KC19maW5hbFBvaW50QgwKCl9jaGFwdGVySWRCDAoK",
            "X2JhcnJpZXJJZEIVChNfcmVmcmVzaE5wY1Bva2VyTnVtQhgKFl9yZWZyZXNo",
            "UGxheWVyUG9rZXJOdW0imgIKCEdhbWVEYXRhEhUKCGluaXRTZWVkGAEgASgF",
            "SACIAQESFgoJZ2FtZVN0YXRlGAIgASgFSAGIAQESFgoJcGFnZUluZGV4GAMg",
            "ASgFSAKIAQESFgoJcGxheWluZ0lkGAQgASgFSAOIAQESEAoDZXhwGAUgASgF",
            "SASIAQESLwoRZGVmZWF0UGxheWVyUm9sZXMYBiADKAsyFC5wYi5EZWZlYXRQ",
            "bGF5ZXJSb2xlEiEKB2JhcnJpZXIYByABKAsyCy5wYi5CYXJyaWVySAWIAQFC",
            "CwoJX2luaXRTZWVkQgwKCl9nYW1lU3RhdGVCDAoKX3BhZ2VJbmRleEIMCgpf",
            "cGxheWluZ0lkQgYKBF9leHBCCgoIX2JhcnJpZXIingEKDEdhbWVQcm9wZXJ0",
            "eRIhCgdhY2NvdW50GAEgASgLMgsucGIuQWNjb3VudEgAiAEBEiEKB3NldHRp",
            "bmcYAiABKAsyCy5wYi5TZXR0aW5nSAGIAQESIwoIZ2FtZURhdGEYAyABKAsy",
            "DC5wYi5HYW1lRGF0YUgCiAEBQgoKCF9hY2NvdW50QgoKCF9zZXR0aW5nQgsK",
            "CV9nYW1lRGF0YWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Account), global::Pb.Account.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Setting), global::Pb.Setting.Parser, new[]{ "Language", "Appearance", "Resolution", "MainVolume", "MusicVolume", "SoundVolume" }, new[]{ "Language", "Appearance", "Resolution", "MainVolume", "MusicVolume", "SoundVolume" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.DefeatPlayerRole), global::Pb.DefeatPlayerRole.Parser, new[]{ "Id", "Diff" }, new[]{ "Id", "Diff" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.Barrier), global::Pb.Barrier.Parser, new[]{ "PokerPile", "NpcPokers", "PlayerPokers", "OtherPokers", "State", "MatchPointA", "MatchPointB", "PokerPosX", "PokerPosY", "FinalPoint", "ChapterId", "BarrierId", "RefreshNpcPokerNum", "RefreshPlayerPokerNum" }, new[]{ "State", "MatchPointA", "MatchPointB", "PokerPosX", "PokerPosY", "FinalPoint", "ChapterId", "BarrierId", "RefreshNpcPokerNum", "RefreshPlayerPokerNum" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.GameData), global::Pb.GameData.Parser, new[]{ "InitSeed", "GameState", "PageIndex", "PlayingId", "Exp", "DefeatPlayerRoles", "Barrier" }, new[]{ "InitSeed", "GameState", "PageIndex", "PlayingId", "Exp", "Barrier" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Pb.GameProperty), global::Pb.GameProperty.Parser, new[]{ "Account", "Setting", "GameData" }, new[]{ "Account", "Setting", "GameData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///账号
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Account : pb::IMessage<Account>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Account> _parser = new pb::MessageParser<Account>(() => new Account());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Account> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account(Account other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Account Clone() {
      return new Account(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Account);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Account other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Account other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  /// <summary>
  ///设置
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Setting : pb::IMessage<Setting>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Setting> _parser = new pb::MessageParser<Setting>(() => new Setting());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Setting> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Setting() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Setting(Setting other) : this() {
      _hasBits0 = other._hasBits0;
      language_ = other.language_;
      appearance_ = other.appearance_;
      resolution_ = other.resolution_;
      mainVolume_ = other.mainVolume_;
      musicVolume_ = other.musicVolume_;
      soundVolume_ = other.soundVolume_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Setting Clone() {
      return new Setting(this);
    }

    /// <summary>Field number for the "language" field.</summary>
    public const int LanguageFieldNumber = 1;
    private readonly static string LanguageDefaultValue = "";

    private string language_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Language {
      get { return language_ ?? LanguageDefaultValue; }
      set {
        language_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "language" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLanguage {
      get { return language_ != null; }
    }
    /// <summary>Clears the value of the "language" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLanguage() {
      language_ = null;
    }

    /// <summary>Field number for the "appearance" field.</summary>
    public const int AppearanceFieldNumber = 2;
    private readonly static int AppearanceDefaultValue = 0;

    private int appearance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Appearance {
      get { if ((_hasBits0 & 1) != 0) { return appearance_; } else { return AppearanceDefaultValue; } }
      set {
        _hasBits0 |= 1;
        appearance_ = value;
      }
    }
    /// <summary>Gets whether the "appearance" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasAppearance {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "appearance" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAppearance() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "resolution" field.</summary>
    public const int ResolutionFieldNumber = 3;
    private readonly static int ResolutionDefaultValue = 0;

    private int resolution_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Resolution {
      get { if ((_hasBits0 & 2) != 0) { return resolution_; } else { return ResolutionDefaultValue; } }
      set {
        _hasBits0 |= 2;
        resolution_ = value;
      }
    }
    /// <summary>Gets whether the "resolution" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasResolution {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "resolution" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResolution() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "mainVolume" field.</summary>
    public const int MainVolumeFieldNumber = 4;
    private readonly static float MainVolumeDefaultValue = 0F;

    private float mainVolume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MainVolume {
      get { if ((_hasBits0 & 4) != 0) { return mainVolume_; } else { return MainVolumeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        mainVolume_ = value;
      }
    }
    /// <summary>Gets whether the "mainVolume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMainVolume {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "mainVolume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMainVolume() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "musicVolume" field.</summary>
    public const int MusicVolumeFieldNumber = 5;
    private readonly static float MusicVolumeDefaultValue = 0F;

    private float musicVolume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float MusicVolume {
      get { if ((_hasBits0 & 8) != 0) { return musicVolume_; } else { return MusicVolumeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        musicVolume_ = value;
      }
    }
    /// <summary>Gets whether the "musicVolume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMusicVolume {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "musicVolume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMusicVolume() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "soundVolume" field.</summary>
    public const int SoundVolumeFieldNumber = 6;
    private readonly static float SoundVolumeDefaultValue = 0F;

    private float soundVolume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float SoundVolume {
      get { if ((_hasBits0 & 16) != 0) { return soundVolume_; } else { return SoundVolumeDefaultValue; } }
      set {
        _hasBits0 |= 16;
        soundVolume_ = value;
      }
    }
    /// <summary>Gets whether the "soundVolume" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSoundVolume {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "soundVolume" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSoundVolume() {
      _hasBits0 &= ~16;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Setting);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Setting other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Language != other.Language) return false;
      if (Appearance != other.Appearance) return false;
      if (Resolution != other.Resolution) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MainVolume, other.MainVolume)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(MusicVolume, other.MusicVolume)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SoundVolume, other.SoundVolume)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasLanguage) hash ^= Language.GetHashCode();
      if (HasAppearance) hash ^= Appearance.GetHashCode();
      if (HasResolution) hash ^= Resolution.GetHashCode();
      if (HasMainVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MainVolume);
      if (HasMusicVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(MusicVolume);
      if (HasSoundVolume) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SoundVolume);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasLanguage) {
        output.WriteRawTag(10);
        output.WriteString(Language);
      }
      if (HasAppearance) {
        output.WriteRawTag(16);
        output.WriteInt32(Appearance);
      }
      if (HasResolution) {
        output.WriteRawTag(24);
        output.WriteInt32(Resolution);
      }
      if (HasMainVolume) {
        output.WriteRawTag(37);
        output.WriteFloat(MainVolume);
      }
      if (HasMusicVolume) {
        output.WriteRawTag(45);
        output.WriteFloat(MusicVolume);
      }
      if (HasSoundVolume) {
        output.WriteRawTag(53);
        output.WriteFloat(SoundVolume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasLanguage) {
        output.WriteRawTag(10);
        output.WriteString(Language);
      }
      if (HasAppearance) {
        output.WriteRawTag(16);
        output.WriteInt32(Appearance);
      }
      if (HasResolution) {
        output.WriteRawTag(24);
        output.WriteInt32(Resolution);
      }
      if (HasMainVolume) {
        output.WriteRawTag(37);
        output.WriteFloat(MainVolume);
      }
      if (HasMusicVolume) {
        output.WriteRawTag(45);
        output.WriteFloat(MusicVolume);
      }
      if (HasSoundVolume) {
        output.WriteRawTag(53);
        output.WriteFloat(SoundVolume);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasLanguage) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Language);
      }
      if (HasAppearance) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Appearance);
      }
      if (HasResolution) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Resolution);
      }
      if (HasMainVolume) {
        size += 1 + 4;
      }
      if (HasMusicVolume) {
        size += 1 + 4;
      }
      if (HasSoundVolume) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Setting other) {
      if (other == null) {
        return;
      }
      if (other.HasLanguage) {
        Language = other.Language;
      }
      if (other.HasAppearance) {
        Appearance = other.Appearance;
      }
      if (other.HasResolution) {
        Resolution = other.Resolution;
      }
      if (other.HasMainVolume) {
        MainVolume = other.MainVolume;
      }
      if (other.HasMusicVolume) {
        MusicVolume = other.MusicVolume;
      }
      if (other.HasSoundVolume) {
        SoundVolume = other.SoundVolume;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Language = input.ReadString();
            break;
          }
          case 16: {
            Appearance = input.ReadInt32();
            break;
          }
          case 24: {
            Resolution = input.ReadInt32();
            break;
          }
          case 37: {
            MainVolume = input.ReadFloat();
            break;
          }
          case 45: {
            MusicVolume = input.ReadFloat();
            break;
          }
          case 53: {
            SoundVolume = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Language = input.ReadString();
            break;
          }
          case 16: {
            Appearance = input.ReadInt32();
            break;
          }
          case 24: {
            Resolution = input.ReadInt32();
            break;
          }
          case 37: {
            MainVolume = input.ReadFloat();
            break;
          }
          case 45: {
            MusicVolume = input.ReadFloat();
            break;
          }
          case 53: {
            SoundVolume = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class DefeatPlayerRole : pb::IMessage<DefeatPlayerRole>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DefeatPlayerRole> _parser = new pb::MessageParser<DefeatPlayerRole>(() => new DefeatPlayerRole());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<DefeatPlayerRole> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefeatPlayerRole() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefeatPlayerRole(DefeatPlayerRole other) : this() {
      _hasBits0 = other._hasBits0;
      id_ = other.id_;
      diff_ = other.diff_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public DefeatPlayerRole Clone() {
      return new DefeatPlayerRole(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private readonly static int IdDefaultValue = 0;

    private int id_;
    /// <summary>
    ///击败的角色Id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Id {
      get { if ((_hasBits0 & 1) != 0) { return id_; } else { return IdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        id_ = value;
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "diff" field.</summary>
    public const int DiffFieldNumber = 2;
    private readonly static int DiffDefaultValue = 0;

    private int diff_;
    /// <summary>
    ///难度
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Diff {
      get { if ((_hasBits0 & 2) != 0) { return diff_; } else { return DiffDefaultValue; } }
      set {
        _hasBits0 |= 2;
        diff_ = value;
      }
    }
    /// <summary>Gets whether the "diff" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDiff {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "diff" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDiff() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as DefeatPlayerRole);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(DefeatPlayerRole other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Diff != other.Diff) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasId) hash ^= Id.GetHashCode();
      if (HasDiff) hash ^= Diff.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasDiff) {
        output.WriteRawTag(16);
        output.WriteInt32(Diff);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasId) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (HasDiff) {
        output.WriteRawTag(16);
        output.WriteInt32(Diff);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (HasDiff) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Diff);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(DefeatPlayerRole other) {
      if (other == null) {
        return;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasDiff) {
        Diff = other.Diff;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Diff = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            Diff = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Barrier : pb::IMessage<Barrier>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Barrier> _parser = new pb::MessageParser<Barrier>(() => new Barrier());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Barrier> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Barrier() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Barrier(Barrier other) : this() {
      _hasBits0 = other._hasBits0;
      pokerPile_ = other.pokerPile_.Clone();
      npcPokers_ = other.npcPokers_.Clone();
      playerPokers_ = other.playerPokers_.Clone();
      otherPokers_ = other.otherPokers_.Clone();
      state_ = other.state_;
      matchPointA_ = other.matchPointA_;
      matchPointB_ = other.matchPointB_;
      pokerPosX_ = other.pokerPosX_;
      pokerPosY_ = other.pokerPosY_;
      finalPoint_ = other.finalPoint_;
      chapterId_ = other.chapterId_;
      barrierId_ = other.barrierId_;
      refreshNpcPokerNum_ = other.refreshNpcPokerNum_;
      refreshPlayerPokerNum_ = other.refreshPlayerPokerNum_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Barrier Clone() {
      return new Barrier(this);
    }

    /// <summary>Field number for the "pokerPile" field.</summary>
    public const int PokerPileFieldNumber = 1;
    private static readonly pb::FieldCodec<int> _repeated_pokerPile_codec
        = pb::FieldCodec.ForInt32(10);
    private readonly pbc::RepeatedField<int> pokerPile_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///牌堆
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PokerPile {
      get { return pokerPile_; }
    }

    /// <summary>Field number for the "npcPokers" field.</summary>
    public const int NpcPokersFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_npcPokers_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> npcPokers_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///npc的牌 
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> NpcPokers {
      get { return npcPokers_; }
    }

    /// <summary>Field number for the "playerPokers" field.</summary>
    public const int PlayerPokersFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_playerPokers_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> playerPokers_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///player的牌
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> PlayerPokers {
      get { return playerPokers_; }
    }

    /// <summary>Field number for the "otherPokers" field.</summary>
    public const int OtherPokersFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_otherPokers_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> otherPokers_ = new pbc::RepeatedField<int>();
    /// <summary>
    ///其他的牌
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> OtherPokers {
      get { return otherPokers_; }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 5;
    private readonly static int StateDefaultValue = 0;

    private int state_;
    /// <summary>
    ///状态 0发牌 1组合 2要牌
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int State {
      get { if ((_hasBits0 & 1) != 0) { return state_; } else { return StateDefaultValue; } }
      set {
        _hasBits0 |= 1;
        state_ = value;
      }
    }
    /// <summary>Gets whether the "state" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasState {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "state" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearState() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "matchPointA" field.</summary>
    public const int MatchPointAFieldNumber = 6;
    private readonly static int MatchPointADefaultValue = 0;

    private int matchPointA_;
    /// <summary>
    ///公共牌的值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MatchPointA {
      get { if ((_hasBits0 & 2) != 0) { return matchPointA_; } else { return MatchPointADefaultValue; } }
      set {
        _hasBits0 |= 2;
        matchPointA_ = value;
      }
    }
    /// <summary>Gets whether the "matchPointA" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMatchPointA {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "matchPointA" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMatchPointA() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "matchPointB" field.</summary>
    public const int MatchPointBFieldNumber = 7;
    private readonly static int MatchPointBDefaultValue = 0;

    private int matchPointB_;
    /// <summary>
    ///手牌的值
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MatchPointB {
      get { if ((_hasBits0 & 4) != 0) { return matchPointB_; } else { return MatchPointBDefaultValue; } }
      set {
        _hasBits0 |= 4;
        matchPointB_ = value;
      }
    }
    /// <summary>Gets whether the "matchPointB" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMatchPointB {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "matchPointB" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMatchPointB() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "pokerPosX" field.</summary>
    public const int PokerPosXFieldNumber = 8;
    private readonly static int PokerPosXDefaultValue = 0;

    private int pokerPosX_;
    /// <summary>
    ///坐标的偏差
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PokerPosX {
      get { if ((_hasBits0 & 8) != 0) { return pokerPosX_; } else { return PokerPosXDefaultValue; } }
      set {
        _hasBits0 |= 8;
        pokerPosX_ = value;
      }
    }
    /// <summary>Gets whether the "pokerPosX" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPokerPosX {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "pokerPosX" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPokerPosX() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "pokerPosY" field.</summary>
    public const int PokerPosYFieldNumber = 9;
    private readonly static int PokerPosYDefaultValue = 0;

    private int pokerPosY_;
    /// <summary>
    ///坐标的偏差
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PokerPosY {
      get { if ((_hasBits0 & 16) != 0) { return pokerPosY_; } else { return PokerPosYDefaultValue; } }
      set {
        _hasBits0 |= 16;
        pokerPosY_ = value;
      }
    }
    /// <summary>Gets whether the "pokerPosY" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPokerPosY {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "pokerPosY" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPokerPosY() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "finalPoint" field.</summary>
    public const int FinalPointFieldNumber = 10;
    private readonly static int FinalPointDefaultValue = 0;

    private int finalPoint_;
    /// <summary>
    ///最终的点数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int FinalPoint {
      get { if ((_hasBits0 & 32) != 0) { return finalPoint_; } else { return FinalPointDefaultValue; } }
      set {
        _hasBits0 |= 32;
        finalPoint_ = value;
      }
    }
    /// <summary>Gets whether the "finalPoint" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFinalPoint {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "finalPoint" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFinalPoint() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "chapterId" field.</summary>
    public const int ChapterIdFieldNumber = 11;
    private readonly static int ChapterIdDefaultValue = 0;

    private int chapterId_;
    /// <summary>
    ///当前章节id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChapterId {
      get { if ((_hasBits0 & 64) != 0) { return chapterId_; } else { return ChapterIdDefaultValue; } }
      set {
        _hasBits0 |= 64;
        chapterId_ = value;
      }
    }
    /// <summary>Gets whether the "chapterId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasChapterId {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "chapterId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearChapterId() {
      _hasBits0 &= ~64;
    }

    /// <summary>Field number for the "barrierId" field.</summary>
    public const int BarrierIdFieldNumber = 12;
    private readonly static int BarrierIdDefaultValue = 0;

    private int barrierId_;
    /// <summary>
    ///关卡id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BarrierId {
      get { if ((_hasBits0 & 128) != 0) { return barrierId_; } else { return BarrierIdDefaultValue; } }
      set {
        _hasBits0 |= 128;
        barrierId_ = value;
      }
    }
    /// <summary>Gets whether the "barrierId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasBarrierId {
      get { return (_hasBits0 & 128) != 0; }
    }
    /// <summary>Clears the value of the "barrierId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearBarrierId() {
      _hasBits0 &= ~128;
    }

    /// <summary>Field number for the "refreshNpcPokerNum" field.</summary>
    public const int RefreshNpcPokerNumFieldNumber = 13;
    private readonly static int RefreshNpcPokerNumDefaultValue = 0;

    private int refreshNpcPokerNum_;
    /// <summary>
    ///刷新npc的牌次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RefreshNpcPokerNum {
      get { if ((_hasBits0 & 256) != 0) { return refreshNpcPokerNum_; } else { return RefreshNpcPokerNumDefaultValue; } }
      set {
        _hasBits0 |= 256;
        refreshNpcPokerNum_ = value;
      }
    }
    /// <summary>Gets whether the "refreshNpcPokerNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRefreshNpcPokerNum {
      get { return (_hasBits0 & 256) != 0; }
    }
    /// <summary>Clears the value of the "refreshNpcPokerNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRefreshNpcPokerNum() {
      _hasBits0 &= ~256;
    }

    /// <summary>Field number for the "refreshPlayerPokerNum" field.</summary>
    public const int RefreshPlayerPokerNumFieldNumber = 14;
    private readonly static int RefreshPlayerPokerNumDefaultValue = 0;

    private int refreshPlayerPokerNum_;
    /// <summary>
    ///刷新玩家的牌次数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RefreshPlayerPokerNum {
      get { if ((_hasBits0 & 512) != 0) { return refreshPlayerPokerNum_; } else { return RefreshPlayerPokerNumDefaultValue; } }
      set {
        _hasBits0 |= 512;
        refreshPlayerPokerNum_ = value;
      }
    }
    /// <summary>Gets whether the "refreshPlayerPokerNum" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRefreshPlayerPokerNum {
      get { return (_hasBits0 & 512) != 0; }
    }
    /// <summary>Clears the value of the "refreshPlayerPokerNum" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRefreshPlayerPokerNum() {
      _hasBits0 &= ~512;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Barrier);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Barrier other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pokerPile_.Equals(other.pokerPile_)) return false;
      if(!npcPokers_.Equals(other.npcPokers_)) return false;
      if(!playerPokers_.Equals(other.playerPokers_)) return false;
      if(!otherPokers_.Equals(other.otherPokers_)) return false;
      if (State != other.State) return false;
      if (MatchPointA != other.MatchPointA) return false;
      if (MatchPointB != other.MatchPointB) return false;
      if (PokerPosX != other.PokerPosX) return false;
      if (PokerPosY != other.PokerPosY) return false;
      if (FinalPoint != other.FinalPoint) return false;
      if (ChapterId != other.ChapterId) return false;
      if (BarrierId != other.BarrierId) return false;
      if (RefreshNpcPokerNum != other.RefreshNpcPokerNum) return false;
      if (RefreshPlayerPokerNum != other.RefreshPlayerPokerNum) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pokerPile_.GetHashCode();
      hash ^= npcPokers_.GetHashCode();
      hash ^= playerPokers_.GetHashCode();
      hash ^= otherPokers_.GetHashCode();
      if (HasState) hash ^= State.GetHashCode();
      if (HasMatchPointA) hash ^= MatchPointA.GetHashCode();
      if (HasMatchPointB) hash ^= MatchPointB.GetHashCode();
      if (HasPokerPosX) hash ^= PokerPosX.GetHashCode();
      if (HasPokerPosY) hash ^= PokerPosY.GetHashCode();
      if (HasFinalPoint) hash ^= FinalPoint.GetHashCode();
      if (HasChapterId) hash ^= ChapterId.GetHashCode();
      if (HasBarrierId) hash ^= BarrierId.GetHashCode();
      if (HasRefreshNpcPokerNum) hash ^= RefreshNpcPokerNum.GetHashCode();
      if (HasRefreshPlayerPokerNum) hash ^= RefreshPlayerPokerNum.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      pokerPile_.WriteTo(output, _repeated_pokerPile_codec);
      npcPokers_.WriteTo(output, _repeated_npcPokers_codec);
      playerPokers_.WriteTo(output, _repeated_playerPokers_codec);
      otherPokers_.WriteTo(output, _repeated_otherPokers_codec);
      if (HasState) {
        output.WriteRawTag(40);
        output.WriteInt32(State);
      }
      if (HasMatchPointA) {
        output.WriteRawTag(48);
        output.WriteInt32(MatchPointA);
      }
      if (HasMatchPointB) {
        output.WriteRawTag(56);
        output.WriteInt32(MatchPointB);
      }
      if (HasPokerPosX) {
        output.WriteRawTag(64);
        output.WriteInt32(PokerPosX);
      }
      if (HasPokerPosY) {
        output.WriteRawTag(72);
        output.WriteInt32(PokerPosY);
      }
      if (HasFinalPoint) {
        output.WriteRawTag(80);
        output.WriteInt32(FinalPoint);
      }
      if (HasChapterId) {
        output.WriteRawTag(88);
        output.WriteInt32(ChapterId);
      }
      if (HasBarrierId) {
        output.WriteRawTag(96);
        output.WriteInt32(BarrierId);
      }
      if (HasRefreshNpcPokerNum) {
        output.WriteRawTag(104);
        output.WriteInt32(RefreshNpcPokerNum);
      }
      if (HasRefreshPlayerPokerNum) {
        output.WriteRawTag(112);
        output.WriteInt32(RefreshPlayerPokerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      pokerPile_.WriteTo(ref output, _repeated_pokerPile_codec);
      npcPokers_.WriteTo(ref output, _repeated_npcPokers_codec);
      playerPokers_.WriteTo(ref output, _repeated_playerPokers_codec);
      otherPokers_.WriteTo(ref output, _repeated_otherPokers_codec);
      if (HasState) {
        output.WriteRawTag(40);
        output.WriteInt32(State);
      }
      if (HasMatchPointA) {
        output.WriteRawTag(48);
        output.WriteInt32(MatchPointA);
      }
      if (HasMatchPointB) {
        output.WriteRawTag(56);
        output.WriteInt32(MatchPointB);
      }
      if (HasPokerPosX) {
        output.WriteRawTag(64);
        output.WriteInt32(PokerPosX);
      }
      if (HasPokerPosY) {
        output.WriteRawTag(72);
        output.WriteInt32(PokerPosY);
      }
      if (HasFinalPoint) {
        output.WriteRawTag(80);
        output.WriteInt32(FinalPoint);
      }
      if (HasChapterId) {
        output.WriteRawTag(88);
        output.WriteInt32(ChapterId);
      }
      if (HasBarrierId) {
        output.WriteRawTag(96);
        output.WriteInt32(BarrierId);
      }
      if (HasRefreshNpcPokerNum) {
        output.WriteRawTag(104);
        output.WriteInt32(RefreshNpcPokerNum);
      }
      if (HasRefreshPlayerPokerNum) {
        output.WriteRawTag(112);
        output.WriteInt32(RefreshPlayerPokerNum);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += pokerPile_.CalculateSize(_repeated_pokerPile_codec);
      size += npcPokers_.CalculateSize(_repeated_npcPokers_codec);
      size += playerPokers_.CalculateSize(_repeated_playerPokers_codec);
      size += otherPokers_.CalculateSize(_repeated_otherPokers_codec);
      if (HasState) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(State);
      }
      if (HasMatchPointA) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MatchPointA);
      }
      if (HasMatchPointB) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MatchPointB);
      }
      if (HasPokerPosX) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PokerPosX);
      }
      if (HasPokerPosY) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PokerPosY);
      }
      if (HasFinalPoint) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalPoint);
      }
      if (HasChapterId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChapterId);
      }
      if (HasBarrierId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BarrierId);
      }
      if (HasRefreshNpcPokerNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RefreshNpcPokerNum);
      }
      if (HasRefreshPlayerPokerNum) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RefreshPlayerPokerNum);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Barrier other) {
      if (other == null) {
        return;
      }
      pokerPile_.Add(other.pokerPile_);
      npcPokers_.Add(other.npcPokers_);
      playerPokers_.Add(other.playerPokers_);
      otherPokers_.Add(other.otherPokers_);
      if (other.HasState) {
        State = other.State;
      }
      if (other.HasMatchPointA) {
        MatchPointA = other.MatchPointA;
      }
      if (other.HasMatchPointB) {
        MatchPointB = other.MatchPointB;
      }
      if (other.HasPokerPosX) {
        PokerPosX = other.PokerPosX;
      }
      if (other.HasPokerPosY) {
        PokerPosY = other.PokerPosY;
      }
      if (other.HasFinalPoint) {
        FinalPoint = other.FinalPoint;
      }
      if (other.HasChapterId) {
        ChapterId = other.ChapterId;
      }
      if (other.HasBarrierId) {
        BarrierId = other.BarrierId;
      }
      if (other.HasRefreshNpcPokerNum) {
        RefreshNpcPokerNum = other.RefreshNpcPokerNum;
      }
      if (other.HasRefreshPlayerPokerNum) {
        RefreshPlayerPokerNum = other.RefreshPlayerPokerNum;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10:
          case 8: {
            pokerPile_.AddEntriesFrom(input, _repeated_pokerPile_codec);
            break;
          }
          case 18:
          case 16: {
            npcPokers_.AddEntriesFrom(input, _repeated_npcPokers_codec);
            break;
          }
          case 26:
          case 24: {
            playerPokers_.AddEntriesFrom(input, _repeated_playerPokers_codec);
            break;
          }
          case 34:
          case 32: {
            otherPokers_.AddEntriesFrom(input, _repeated_otherPokers_codec);
            break;
          }
          case 40: {
            State = input.ReadInt32();
            break;
          }
          case 48: {
            MatchPointA = input.ReadInt32();
            break;
          }
          case 56: {
            MatchPointB = input.ReadInt32();
            break;
          }
          case 64: {
            PokerPosX = input.ReadInt32();
            break;
          }
          case 72: {
            PokerPosY = input.ReadInt32();
            break;
          }
          case 80: {
            FinalPoint = input.ReadInt32();
            break;
          }
          case 88: {
            ChapterId = input.ReadInt32();
            break;
          }
          case 96: {
            BarrierId = input.ReadInt32();
            break;
          }
          case 104: {
            RefreshNpcPokerNum = input.ReadInt32();
            break;
          }
          case 112: {
            RefreshPlayerPokerNum = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10:
          case 8: {
            pokerPile_.AddEntriesFrom(ref input, _repeated_pokerPile_codec);
            break;
          }
          case 18:
          case 16: {
            npcPokers_.AddEntriesFrom(ref input, _repeated_npcPokers_codec);
            break;
          }
          case 26:
          case 24: {
            playerPokers_.AddEntriesFrom(ref input, _repeated_playerPokers_codec);
            break;
          }
          case 34:
          case 32: {
            otherPokers_.AddEntriesFrom(ref input, _repeated_otherPokers_codec);
            break;
          }
          case 40: {
            State = input.ReadInt32();
            break;
          }
          case 48: {
            MatchPointA = input.ReadInt32();
            break;
          }
          case 56: {
            MatchPointB = input.ReadInt32();
            break;
          }
          case 64: {
            PokerPosX = input.ReadInt32();
            break;
          }
          case 72: {
            PokerPosY = input.ReadInt32();
            break;
          }
          case 80: {
            FinalPoint = input.ReadInt32();
            break;
          }
          case 88: {
            ChapterId = input.ReadInt32();
            break;
          }
          case 96: {
            BarrierId = input.ReadInt32();
            break;
          }
          case 104: {
            RefreshNpcPokerNum = input.ReadInt32();
            break;
          }
          case 112: {
            RefreshPlayerPokerNum = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///游戏
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameData : pb::IMessage<GameData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameData> _parser = new pb::MessageParser<GameData>(() => new GameData());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameData(GameData other) : this() {
      _hasBits0 = other._hasBits0;
      initSeed_ = other.initSeed_;
      gameState_ = other.gameState_;
      pageIndex_ = other.pageIndex_;
      playingId_ = other.playingId_;
      exp_ = other.exp_;
      defeatPlayerRoles_ = other.defeatPlayerRoles_.Clone();
      barrier_ = other.barrier_ != null ? other.barrier_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameData Clone() {
      return new GameData(this);
    }

    /// <summary>Field number for the "initSeed" field.</summary>
    public const int InitSeedFieldNumber = 1;
    private readonly static int InitSeedDefaultValue = 0;

    private int initSeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int InitSeed {
      get { if ((_hasBits0 & 1) != 0) { return initSeed_; } else { return InitSeedDefaultValue; } }
      set {
        _hasBits0 |= 1;
        initSeed_ = value;
      }
    }
    /// <summary>Gets whether the "initSeed" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasInitSeed {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "initSeed" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearInitSeed() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "gameState" field.</summary>
    public const int GameStateFieldNumber = 2;
    private readonly static int GameStateDefaultValue = 0;

    private int gameState_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GameState {
      get { if ((_hasBits0 & 2) != 0) { return gameState_; } else { return GameStateDefaultValue; } }
      set {
        _hasBits0 |= 2;
        gameState_ = value;
      }
    }
    /// <summary>Gets whether the "gameState" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasGameState {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "gameState" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearGameState() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "pageIndex" field.</summary>
    public const int PageIndexFieldNumber = 3;
    private readonly static int PageIndexDefaultValue = 0;

    private int pageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PageIndex {
      get { if ((_hasBits0 & 4) != 0) { return pageIndex_; } else { return PageIndexDefaultValue; } }
      set {
        _hasBits0 |= 4;
        pageIndex_ = value;
      }
    }
    /// <summary>Gets whether the "pageIndex" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPageIndex {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "pageIndex" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPageIndex() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "playingId" field.</summary>
    public const int PlayingIdFieldNumber = 4;
    private readonly static int PlayingIdDefaultValue = 0;

    private int playingId_;
    /// <summary>
    ///当前玩角色Id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PlayingId {
      get { if ((_hasBits0 & 8) != 0) { return playingId_; } else { return PlayingIdDefaultValue; } }
      set {
        _hasBits0 |= 8;
        playingId_ = value;
      }
    }
    /// <summary>Gets whether the "playingId" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlayingId {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "playingId" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlayingId() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "exp" field.</summary>
    public const int ExpFieldNumber = 5;
    private readonly static int ExpDefaultValue = 0;

    private int exp_;
    /// <summary>
    ///经验
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Exp {
      get { if ((_hasBits0 & 16) != 0) { return exp_; } else { return ExpDefaultValue; } }
      set {
        _hasBits0 |= 16;
        exp_ = value;
      }
    }
    /// <summary>Gets whether the "exp" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasExp {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "exp" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearExp() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "defeatPlayerRoles" field.</summary>
    public const int DefeatPlayerRolesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Pb.DefeatPlayerRole> _repeated_defeatPlayerRoles_codec
        = pb::FieldCodec.ForMessage(50, global::Pb.DefeatPlayerRole.Parser);
    private readonly pbc::RepeatedField<global::Pb.DefeatPlayerRole> defeatPlayerRoles_ = new pbc::RepeatedField<global::Pb.DefeatPlayerRole>();
    /// <summary>
    ///击败的
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Pb.DefeatPlayerRole> DefeatPlayerRoles {
      get { return defeatPlayerRoles_; }
    }

    /// <summary>Field number for the "barrier" field.</summary>
    public const int BarrierFieldNumber = 7;
    private global::Pb.Barrier barrier_;
    /// <summary>
    ///关卡
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Barrier Barrier {
      get { return barrier_; }
      set {
        barrier_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (InitSeed != other.InitSeed) return false;
      if (GameState != other.GameState) return false;
      if (PageIndex != other.PageIndex) return false;
      if (PlayingId != other.PlayingId) return false;
      if (Exp != other.Exp) return false;
      if(!defeatPlayerRoles_.Equals(other.defeatPlayerRoles_)) return false;
      if (!object.Equals(Barrier, other.Barrier)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasInitSeed) hash ^= InitSeed.GetHashCode();
      if (HasGameState) hash ^= GameState.GetHashCode();
      if (HasPageIndex) hash ^= PageIndex.GetHashCode();
      if (HasPlayingId) hash ^= PlayingId.GetHashCode();
      if (HasExp) hash ^= Exp.GetHashCode();
      hash ^= defeatPlayerRoles_.GetHashCode();
      if (barrier_ != null) hash ^= Barrier.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasInitSeed) {
        output.WriteRawTag(8);
        output.WriteInt32(InitSeed);
      }
      if (HasGameState) {
        output.WriteRawTag(16);
        output.WriteInt32(GameState);
      }
      if (HasPageIndex) {
        output.WriteRawTag(24);
        output.WriteInt32(PageIndex);
      }
      if (HasPlayingId) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayingId);
      }
      if (HasExp) {
        output.WriteRawTag(40);
        output.WriteInt32(Exp);
      }
      defeatPlayerRoles_.WriteTo(output, _repeated_defeatPlayerRoles_codec);
      if (barrier_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Barrier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasInitSeed) {
        output.WriteRawTag(8);
        output.WriteInt32(InitSeed);
      }
      if (HasGameState) {
        output.WriteRawTag(16);
        output.WriteInt32(GameState);
      }
      if (HasPageIndex) {
        output.WriteRawTag(24);
        output.WriteInt32(PageIndex);
      }
      if (HasPlayingId) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayingId);
      }
      if (HasExp) {
        output.WriteRawTag(40);
        output.WriteInt32(Exp);
      }
      defeatPlayerRoles_.WriteTo(ref output, _repeated_defeatPlayerRoles_codec);
      if (barrier_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(Barrier);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasInitSeed) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(InitSeed);
      }
      if (HasGameState) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GameState);
      }
      if (HasPageIndex) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageIndex);
      }
      if (HasPlayingId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayingId);
      }
      if (HasExp) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Exp);
      }
      size += defeatPlayerRoles_.CalculateSize(_repeated_defeatPlayerRoles_codec);
      if (barrier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Barrier);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameData other) {
      if (other == null) {
        return;
      }
      if (other.HasInitSeed) {
        InitSeed = other.InitSeed;
      }
      if (other.HasGameState) {
        GameState = other.GameState;
      }
      if (other.HasPageIndex) {
        PageIndex = other.PageIndex;
      }
      if (other.HasPlayingId) {
        PlayingId = other.PlayingId;
      }
      if (other.HasExp) {
        Exp = other.Exp;
      }
      defeatPlayerRoles_.Add(other.defeatPlayerRoles_);
      if (other.barrier_ != null) {
        if (barrier_ == null) {
          Barrier = new global::Pb.Barrier();
        }
        Barrier.MergeFrom(other.Barrier);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            InitSeed = input.ReadInt32();
            break;
          }
          case 16: {
            GameState = input.ReadInt32();
            break;
          }
          case 24: {
            PageIndex = input.ReadInt32();
            break;
          }
          case 32: {
            PlayingId = input.ReadInt32();
            break;
          }
          case 40: {
            Exp = input.ReadInt32();
            break;
          }
          case 50: {
            defeatPlayerRoles_.AddEntriesFrom(input, _repeated_defeatPlayerRoles_codec);
            break;
          }
          case 58: {
            if (barrier_ == null) {
              Barrier = new global::Pb.Barrier();
            }
            input.ReadMessage(Barrier);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            InitSeed = input.ReadInt32();
            break;
          }
          case 16: {
            GameState = input.ReadInt32();
            break;
          }
          case 24: {
            PageIndex = input.ReadInt32();
            break;
          }
          case 32: {
            PlayingId = input.ReadInt32();
            break;
          }
          case 40: {
            Exp = input.ReadInt32();
            break;
          }
          case 50: {
            defeatPlayerRoles_.AddEntriesFrom(ref input, _repeated_defeatPlayerRoles_codec);
            break;
          }
          case 58: {
            if (barrier_ == null) {
              Barrier = new global::Pb.Barrier();
            }
            input.ReadMessage(Barrier);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///游戏财产
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class GameProperty : pb::IMessage<GameProperty>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameProperty> _parser = new pb::MessageParser<GameProperty>(() => new GameProperty());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameProperty> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Pb.ProtoReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameProperty() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameProperty(GameProperty other) : this() {
      account_ = other.account_ != null ? other.account_.Clone() : null;
      setting_ = other.setting_ != null ? other.setting_.Clone() : null;
      gameData_ = other.gameData_ != null ? other.gameData_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameProperty Clone() {
      return new GameProperty(this);
    }

    /// <summary>Field number for the "account" field.</summary>
    public const int AccountFieldNumber = 1;
    private global::Pb.Account account_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Account Account {
      get { return account_; }
      set {
        account_ = value;
      }
    }

    /// <summary>Field number for the "setting" field.</summary>
    public const int SettingFieldNumber = 2;
    private global::Pb.Setting setting_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.Setting Setting {
      get { return setting_; }
      set {
        setting_ = value;
      }
    }

    /// <summary>Field number for the "gameData" field.</summary>
    public const int GameDataFieldNumber = 3;
    private global::Pb.GameData gameData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Pb.GameData GameData {
      get { return gameData_; }
      set {
        gameData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameProperty);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameProperty other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Account, other.Account)) return false;
      if (!object.Equals(Setting, other.Setting)) return false;
      if (!object.Equals(GameData, other.GameData)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (account_ != null) hash ^= Account.GetHashCode();
      if (setting_ != null) hash ^= Setting.GetHashCode();
      if (gameData_ != null) hash ^= GameData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (account_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Account);
      }
      if (setting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Setting);
      }
      if (gameData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GameData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (account_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Account);
      }
      if (setting_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Setting);
      }
      if (gameData_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GameData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (account_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Account);
      }
      if (setting_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Setting);
      }
      if (gameData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GameData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameProperty other) {
      if (other == null) {
        return;
      }
      if (other.account_ != null) {
        if (account_ == null) {
          Account = new global::Pb.Account();
        }
        Account.MergeFrom(other.Account);
      }
      if (other.setting_ != null) {
        if (setting_ == null) {
          Setting = new global::Pb.Setting();
        }
        Setting.MergeFrom(other.Setting);
      }
      if (other.gameData_ != null) {
        if (gameData_ == null) {
          GameData = new global::Pb.GameData();
        }
        GameData.MergeFrom(other.GameData);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (account_ == null) {
              Account = new global::Pb.Account();
            }
            input.ReadMessage(Account);
            break;
          }
          case 18: {
            if (setting_ == null) {
              Setting = new global::Pb.Setting();
            }
            input.ReadMessage(Setting);
            break;
          }
          case 26: {
            if (gameData_ == null) {
              GameData = new global::Pb.GameData();
            }
            input.ReadMessage(GameData);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (account_ == null) {
              Account = new global::Pb.Account();
            }
            input.ReadMessage(Account);
            break;
          }
          case 18: {
            if (setting_ == null) {
              Setting = new global::Pb.Setting();
            }
            input.ReadMessage(Setting);
            break;
          }
          case 26: {
            if (gameData_ == null) {
              GameData = new global::Pb.GameData();
            }
            input.ReadMessage(GameData);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
