syntax = "proto3";
package pb;

//账号
message Account{
}

//设置
message Setting{
  optional string language = 1;
  optional int32 appearance = 2;
  optional int32 resolution = 3;
  optional float mainVolume = 4;
  optional float musicVolume = 5;
  optional float soundVolume = 6;
}

message DefeatPlayerRole{
  optional int32 id = 1;				//击败的角色Id
  optional int32 diff= 2;				//难度
}

message Barrier{
  repeated int32 pokerPile = 1;     	//牌堆
  repeated int32 npcPokers = 2;     	//npc的牌 
  repeated int32 playerPokers = 3;  	//player的牌
  repeated int32 otherPokers = 4;  	  //其他的牌
  optional int32 state = 5;           //状态 0发牌 1组合 2要牌
  optional int32 matchPointA = 6;     //公共牌的值
  optional int32 matchPointB = 7;     //手牌的值
  optional int32 pokerPosX = 8;  	    //坐标的偏差
  optional int32 pokerPosY = 9;       //坐标的偏差
  optional int32 finalPoint = 10;     //最终的点数
  optional int32 chapterId = 11;             //当前章节id
  optional int32 barrierId = 12;             //关卡id
  optional int32 refreshNpcPokerNum = 13;    //刷新npc的牌次数
  optional int32 refreshPlayerPokerNum = 14; //刷新玩家的牌次数
}

//游戏
message GameData{
  optional int32 initSeed = 1;
  optional int32 gameState = 2;
  optional int32 pageIndex = 3;		
  optional int32 playingId = 4; 		              //当前玩角色Id
  optional int32 exp = 5;   			                //经验
  repeated DefeatPlayerRole defeatPlayerRoles = 6;//击败的
  optional Barrier barrier = 7;                   //关卡
}

//游戏财产
message GameProperty{
  optional Account account = 1;
  optional Setting setting = 2;
  optional GameData gameData = 3;
}

//protoc --proto_path=. --csharp_out=. proto.proto
